import mongoose, { Document, Schema } from 'mongoose';

// Only file metadata is stored in the database; the binary is served from /uploads/images/
export interface IDriveImage extends Document {
  filename: string;     // unique disk filename generated by Multer
  originalName: string; // original filename from the browser
  mimetype: string;
  size: number;
  owner: mongoose.Types.ObjectId;
  createdAt: Date;
}

const DriveImageSchema: Schema = new Schema({
  filename: { type: String, required: true },
  originalName: { type: String, required: true },
  mimetype: { type: String, required: true },
  size: { type: Number, required: true },
  owner: { type: Schema.Types.ObjectId, ref: 'User', required: true }
}, { timestamps: true });

export default mongoose.model<IDriveImage>('DriveImage', DriveImageSchema);
